---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "stackl.agent" . }}
  labels:
    {{ include "stackl.labels" . | nindent 4 }}
    component: agent
{{- with .Values.agentServiceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2}}
{{- end}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "stackl.agent" . }}-jobs
  labels:
    {{ include "stackl.labels" . | nindent 4 }}
    component: agent
rules:
  - apiGroups: ["*"]
    resources:
      - jobs
      - configmaps
    verbs:
      - create
      - get
      - list
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - pods/status
    verbs:
      - get
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{ include "stackl.labels" . | nindent 4 }}
    component: agent
  name: {{ template "stackl.agent" . }}
roleRef:
  name: {{ template "stackl.agent" . }}-jobs
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "stackl.agent" . }}
    namespace: {{ .Release.Namespace }}
